### ISSUE TITLE
[BUG] README中的描述不够完善

### ISSUE THREAD

**Issue by pcdlrzxx** [jar-analyzer/jar-obfuscator#10]
发现了README中的一些描述问题：

1、经测试，当`obfuscatePackage`和`rootPackages`都不配置时，即使其他的加密配置项都设置为true，处理后的jar仍旧是未混淆和未加密的，不过可以正常运行。当这两项中任意一项或两项都配置了后，就能得到正确混淆后的jar包。所以关于这两项的注释，可能需要完善一下

2、`java -XX:+DisableAttachMechanism -agentpath:decrypter.dll=PACKAGE_NAME=com.your.pack,KEY=your-key --jar your-jar.jar`这个地方应该是写错了，其中的`--jar`应该是`-jar`吧

**Comment by 4ra1n** [comment]
感谢，我处理下

**Comment by 4ra1n** [comment]
https://github.com/jar-analyzer/jar-obfuscator/commit/b1323daf5247abb2b82b3eab3743ba7805edcb9e

**Comment by pcdlrzxx** [comment]
收到，感谢，那我先把这个问题关了
