### ISSUE TITLE
[BUG] 应该忽略包含 native 方法类的混淆

### ISSUE THREAD

**Issue by 4ra1n** [jar-analyzer/jar-obfuscator#15]
JNI 是固定的，不能修改

**Comment by 4ra1n** [comment]
JNI 类是不能混淆的，类名和方法名都不能混淆

临时的办法是：使用 classBlackList 

之后的解决是检测 native 跳过类

**Comment by pcdlrzxx** [comment]
有时候确实是有很多类名不能混淆，不管是框架方法的限制还是业务方法的限制，大佬考虑把 classBlackList 也做成支持正则吗，现在的方式如果这一项有许多要配置的，那会写的非常长

**Comment by 4ra1n** [comment]
已经实现了 native 方法的忽略

classBlackList 我看一下

**Comment by 4ra1n** [comment]
0.1.0
