### ISSUE TITLE
关于C代码的部分疑问

### ISSUE THREAD

**Issue by pcdlrzxx** [jar-analyzer/jar-obfuscator#16]
@4ra1n
大佬，我最近在把这个项目改为支持Windows 32位系统，然后遇到了这个问题：当我把编译好的32位 DLL 放到目录下然后去执行我的 JAVA 程序，很自然的报错了（ORZ），然后我就在C代码里加了很多输出，看看到底在哪步出错了，结果就定位到了下面这段代码，具体是这一行`HMODULE moduleHandle = LoadLibrary("jvm.dll");`，试了很多方法都不行（毕竟我不太会C），最后我就把这段代码全删了，再编译后把 DLL 放到 JAVA 程序目录下再去执行，结果神奇的是居然成功了。

https://github.com/jar-analyzer/jar-obfuscator/blob/main/native/start_windows.c#L238-L261

然后我想问的是，这一段代码到底是起到了什么作用呢，我可以把它删除掉吗？

**Comment by 4ra1n** [comment]
这段代码是可以删掉的，禁用 gHotSpotVMStructs 是为了防止被黑客通过 HSDB 方式 dump 字节码导致泄露，可能这种方式在 32 位里是不支持的

**Comment by pcdlrzxx** [comment]
大佬，我知道问题出在哪了（我觉得根本原因大概率不会是`LoadLibrary`或者禁用`gHotSpotVMStructs`）。昨天我一步一步调试程序，发现最终问题出在这一句`strcpy((char *) KEY, (char *) v2);`，然后我就去网上查了`strcpy`函数的具体解释，发现正确的用法应该是`目标数组的长度需要大于等于源数组长度再加1`（为了存字符串终止符，即'\0'），于是我就按照下面这样改了代码，重新编译生成DLL，再放到32位和64位下去执行，就都没问题了。
```
    // SET PACKAGE_NAME
    PACKAGE_NAME = (char *) malloc(strlen((char *) v1) + 1);
    strcpy(PACKAGE_NAME, (char *) v1);
    
    // SET KEY
    KEY = (unsigned char *) malloc(strlen((char *) v2) + 1);
    strcpy((char *) KEY, (char *) v2);
```
至于之前的写法为什么在64位中没有问题，这个我就不太清楚了，大概还是由于内存空间及分配规则的差异性导致的。

如果大佬需要测试一下32位的问题，我这边可以给予一些帮助，之后我会再研究一下如何在Mac上使用。

**Comment by 4ra1n** [comment]
感谢，你可以提个 MR 修复下 strcpy 用法的 BUG
然后你可以把 32 位的 DLL 也提交下，比如 Load DLL 之前判断下当前 32 还是 64 位，然后根据文件名进行选择

Mac OS 会更麻烦一些

**Comment by pcdlrzxx** [comment]
好的，不过我想先试试能不能一并把Mac的也弄了，要是顺利的话，到时候就可以一起提交

**Comment by 4ra1n** [comment]
可以的

Thanks

**Comment by 4ra1n** [comment]
先关闭了，有新的进展/问题/PR等内容，可以再提ISSUE哦
