### ISSUE TITLE
[BUG] CLASS.GETRESOURCE 无法以目录获取

### ISSUE THREAD

**Issue by tckkct** [jar-analyzer/jar-obfuscator#18]
**师傅您好，我尝试在对java swing UI的项目进行混淆时出现了问题，这里以哥斯拉为例，当我对部分代码或者全部代码混淆时，就会出现create dir jar-obfuscator-temp error的代码错误，然后混淆后的jar包不能运行或运行后部分模块消失，是config.yaml没配置好吗？**

**Comment by 4ra1n** [comment]
发一下具体的报错内容，jar-obfuscator 报错内容 以及混淆后的 jar 启动报错内容

**Comment by T0mina1** [comment]
老师你好，例如我设置config.yaml为对core.shell模块进行混淆
![image](https://github.com/jar-analyzer/jar-obfuscator/assets/144421609/833bca5a-9c4e-41f3-a5a1-0ea02eb20b00)
运行混淆
![image](https://github.com/jar-analyzer/jar-obfuscator/assets/144421609/3db911e4-61c3-42f3-bb38-1a869aa58120)
可正常运行jar包，但是功能缺失了
![image](https://github.com/jar-analyzer/jar-obfuscator/assets/144421609/cfc80702-5ced-4aac-bf42-9868c4d9208b)
点击该模块的报错信息，这种情况应该是我config.yaml文件没配置好吧
![image](https://github.com/jar-analyzer/jar-obfuscator/assets/144421609/031c233f-f64f-421f-a050-897fbe47d707)

**Comment by T0mina1** [comment]
师傅你好，非常感谢你的回复，我关闭了你说的这些参数后，也没有办法正常运行，我仅设置obfuscatePackage
与rootPackages也会报错，两种操作报错都与上面的内容相同。我找了其他的java swing UI的项目，部分程序能正常加密。真的很奇怪，师傅您可以试一下，用的就是北辰老师这个工具做的测试，https://github.com/BeichenDream/Godzilla

**Comment by 4ra1n** [comment]
我修复了这个问题，现在 GODZILLA 可以正常获得 PAYLOAD PLUGINS 等信息了，还没有发新版本，你可以自己 MVN PACKAGE 下试试

![image](https://github.com/jar-analyzer/jar-obfuscator/assets/34726933/28a6ea4b-b255-4610-ba95-43092e345fcd)

**Comment by T0mina1** [comment]
谢谢师傅，问题解决了，学习到了

**Comment by 4ra1n** [comment]
0.2.0
