### ISSUE TITLE
[FEAT] 支持 ANDROID

### ISSUE THREAD

**Issue by df13954** [jar-analyzer/jar-obfuscator#2]
看到是对jar进行混淆，这种情况下能否适配到Android中呢

**Comment by 4ra1n** [comment]
这个暂不支持，因为我对 ANDROID 不太了解，如果有大佬愿意一起做最好了

**Comment by df13954** [comment]
> 这个暂不支持，因为我对 ANDROID 不太了解，如果有大佬愿意一起做最好了

我也想添砖加瓦，但是技术太菜了
