### ISSUE TITLE
顺便支持下 aar 文件?

### ISSUE THREAD

**Issue by oorrnae** [jar-analyzer/jar-obfuscator#20]
aar 文件也是 jar 格式的. 作为函数库, 没有 Main. 

经过测试只开启混淆字符串好像无法正常工作.

**Comment by 4ra1n** [comment]
aar 文件的组成好像是包含 jar 文件

如果要混淆可以试试解压 aar 得到 jar 后进行混淆再打包回去

目前不打算对安卓进行支持，编写该项目起初的目的是对于普通的 JAVA 程序
