### ISSUE TITLE
[BUG] 常见疑问和解答

### ISSUE THREAD

**Issue by pcdlrzxx** [jar-analyzer/jar-obfuscator#7]
大佬，你好！非常佩服能写出这么牛逼的工具，今天我也很期待的做了一些测试，然后有一些疑问如下：

1、貌似有一个bug，就是假如混淆了A类中重写的toString方法，然后在别的类中执行类似System.out.println(A)的时候，无法得到重写后的结果，只有将toString方法加入到配置文件中的methodBlackList才行。

2、混淆后如果产生了报错，信息基本是不可读的，不知道现在有解析堆栈追踪的方法吗

3、目前貌似只能对单个的jar进行混淆，有考虑集成到maven中，在maven构建项目时就进行混淆，这样就能适用于多模块构建混淆了

暂时想到的就这些，多谢大佬分享的牛逼技术，希望继续加油！

6月6日补充：

4、每次执行混淆后，好像都会额外生成一个新的class文件（显示声明了所用到的AES KEY和解密方法）。在测试过程中我发现，有的jar包删除该class文件，仍能正常执行，但有的jar包删除后执行就会报错找不到该class文件。请问这个class文件作用是什么呢，为什么会出现这种情况呢？还有就是，反编译混淆的jar包时，是不是要利用这个class文件，才能真正得到最原始的java代码呢？

5、用加号连接的字符串，貌似没有采用AES进行加密混淆，简单的反编译就能直接看到原始字符串

**Comment by 4ra1n** [comment]
第一个问题

现在重写确实存在问题，只能手动设置黑名单，例如 JAVA ASM 的 visit.* 等继承/重写方法

这个问题我暂时想不到什么好办法，每个人的 JAR 和依赖不一样，比较难找到一种通用办法

比如一个方法是不是重写方法，在 CLASS 层不太好判断，需要看父类的方法和描述，对比当前的类

暂时想不到什么好办法，只能不同的用户根据不同的引用，逐渐和慢慢调整参数到最佳

**Comment by 4ra1n** [comment]
第二个问题

混淆后的报错问题

首先不要开启 `enableDeleteCompileInfo` 删除编译信息，要保留

然后可以反编译混淆后的 JAR 根据报错行号分析原因

控制变量法，只开启某一个具体的混淆参数，以此开启并逐个排查问题

最后，可以 IDEA Rebug Debug 这个 JAR 
- -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
- IDEA ADD CLASSPATH 然后下断点

**Comment by 4ra1n** [comment]
第三个问题

MAVEN 插件的话

确实有必要，以后学习下怎么做 MAVEN 插件

**Comment by pcdlrzxx** [comment]
感谢回复！

针对第二点的反编译，那我得去研究研究，之前没有接触过代码安全这块，编译和反编译也了解的比较少。

总之还是很感谢，之后我也会一直关注的，希望功能越来越强大。

**Comment by pcdlrzxx** [comment]
@4ra1n 大佬你好，我今天测试又遇到了一个疑问，已经更新到描述里了，麻烦看一下，谢谢！

**Comment by 4ra1n** [comment]
新增了一个 CLASS 主要是做 字符串的 AES 解密，因为混淆过程我对所有字符串进行了 AES 加密

这个类之后我考虑做成迷惑用户的系统类，例如 org.apache.commons.XXX 这种

**Comment by 4ra1n** [comment]
嗯，我之后研究下

**Comment by 4ra1n** [comment]
这个问题分为两个子问题，现在关闭该问题

https://github.com/jar-analyzer/jar-obfuscator/issues/8

https://github.com/jar-analyzer/jar-obfuscator/issues/9
